Create custom rest route
simun-ivanac/wordpress-assignment pull request #2
Opened 2021-07-02 11:30 UTC by simun-ivanac

Please check it out!
No need to spare me :)

2021-07-02 11:38 UTC, IvanGrginovInf requested changes
Minor comment regarding `FetchPublicApiData` being a `Service` unnecessarily and using / setting credentials, otherwise looks great!

2021-07-02 11:38 UTC, IvanGrginovInf commented on src/Rest/FetchPublicApiData.php
> +		$this->apiKey = '0700b5c5a1094afe7e084b6181b6491d';
Credentials should usually be saved somewhere where it's a) safe b) won't be committed to the repository.

For purposes of this task, it's enough if you just put this in a constant inside `wp-config.php` and then load the constant here inside `$this->apiKey = YOUR_SECRET_CONSTANT`.

2021-07-02 11:38 UTC, IvanGrginovInf commented on src/Rest/FetchPublicApiData.php
> +class FetchPublicApiData implements ServiceInterface
No need for this class to be a `Service`. Services are just things that do `add_action()` or `add_filter()` (inside the `register()` method which is empty in this Class).

2021-07-02 11:38 UTC, IvanGrginovInf commented on src/Rest/FetchPublicApiData.php
> +	}
See comment above, this class doesn't need to be a service, you can remove this method.

2021-07-02 11:38 UTC, IvanGrginovInf commented on src/Rest/Routes/NewsRouteRoute.php
> +	public function __construct(FetchPublicApiData $apiData)
Nice usage of dependency injection + documenting the property!

2021-07-02 11:41 UTC, simun-ivanac commented on src/Rest/FetchPublicApiData.php
> +		$this->apiKey = '0700b5c5a1094afe7e084b6181b6491d';
Damn, I forgot about that!
Fixing it right away.

2021-07-02 11:42 UTC, simun-ivanac commented
Thanks for feedback. I'm on it!

2021-07-02 12:39 UTC, IvanGrginovInf approved these changes
👌

2021-07-03 10:32 UTC, dingo-d commented on src/Rest/FetchPublicApiData.php
> +		$this->apiKey = API_KEY;
This is a good way to fetch data, but can you tell me how the app will behave if you forgot to set these constants in the `wp-config.php`?

2021-07-03 10:34 UTC, dingo-d commented on src/Rest/FetchPublicApiData.php
> +			$baseUrl .= '&';
Is there a WordPress-specific function that could do this for you? One thing we always want to do, when working within a framework, is to always utilize all of its functionality.

Added benefit of this is that such functions often have additional checks that will help you in the long run 🙂

2021-07-03 10:36 UTC, dingo-d commented on src/Rest/FetchPublicApiData.php
> +		$response = \wp_remote_get($baseUrl);
Is there, maybe, a way to add the access key such that it won't be added as a query parameter? What would be the benefit of this approach vs just adding it as a URL query string?

Hint: think about security 😄

2021-07-03 10:39 UTC, dingo-d commented on src/Rest/Routes/NewsRouteRoute.php
> +		$params = $this->sanitizeParameters($request->get_params());
Like that you abstracted this as a helper method 👍🏼

2021-07-03 10:39 UTC, dingo-d requested changes
Left you some questions. Well done on the DI and usage of abstraction 👍🏼

2021-07-04 10:00 UTC, simun-ivanac commented on src/Rest/FetchPublicApiData.php
> +		$this->apiKey = API_KEY;
Depends :blush: 
If WP_DEBUG is true, it would throw an error since it's undefined constant.
If WP_DEBUG is false, it would be invalid url or unauthorized request.

2021-07-04 10:01 UTC, simun-ivanac commented on src/Rest/FetchPublicApiData.php
> +			$baseUrl .= '&';
I found 2 WordPress functions to create URL with.
1st is add_query_arg().
2nd is build_query().
Add_query_arg() builds whole url, while build_query() just adds extra parameters to existing base string.
Add_query_arg uses build_query() in its source code anyway, so its obviously better choice.

2021-07-04 10:03 UTC, simun-ivanac commented on src/Rest/FetchPublicApiData.php
> +		$response = \wp_remote_get($baseUrl);
Yes, to send authorization key in HTTP header of a request :smiley: 
That way it wont be visible to others in logs or via request sniffing.

Public API which I used didn't support this, so I had to changed it.
But, its fixed now.

2021-07-04 10:05 UTC, simun-ivanac commented on src/Rest/Routes/NewsRouteRoute.php
> +		$params = $this->sanitizeParameters($request->get_params());
Thank you :+1:

2021-07-05 08:19 UTC, dingo-d commented on src/Rest/FetchPublicApiData.php
> +			$baseUrl .= '&';
Yup that's correct 👍🏼

2021-07-05 08:20 UTC, dingo-d commented on src/Rest/FetchPublicApiData.php
> +		$response = \wp_remote_get($baseUrl);
Awesome! This is one of the first things that any pentest company will return to us as a potential vulnerability. Especially if you're passing an authentication key that should be secret.

👍🏼

2021-07-05 08:20 UTC, dingo-d approved these changes

2021-07-05 09:12 UTC, merged