Feature/create custom block
simun-ivanac/wordpress-assignment pull request #3
Opened 2021-07-07 17:20 UTC by simun-ivanac

Please review my code!
I know it's not perfect but I want to improve it as much as possible.
Feel free to point out every little thing that needs to be changed.

2021-07-08 09:38 UTC, dingo-d commented
Just to say that we haven't forgotten about you, but we are a bit busy, so we'll probably review this a bit later today 🙂

2021-07-08 09:45 UTC, IvanGrginovInf requested changes
Left a couple of comments / suggestions but otherwise looking real good, keep it up!

2021-07-08 09:45 UTC, IvanGrginovInf commented on src/Blocks/custom/latest-posts/latest-posts.php
> +		<?php foreach ($apiNews as $key => $item) : ?>
Try to use `foreach() {}` syntax rather than `foreach() :` if possible. The `:` makes it impossible for the editor to detect where a codeblock ends and can get quite messy when you have multiple nested loops / conditionals.

2021-07-08 09:45 UTC, IvanGrginovInf commented on src/Blocks/custom/latest-posts/latest-posts.php
> +					'buttonContent' => __('Load More', 'Assignment'),
Text domain should be written lowercase (that's a bug in the current version of libs where text domain is uppercase)

```suggestion
					'buttonContent' => __('Load More', 'assignment'),
```

Also, it's great you made the text translatable! Would you know how you could make it translatable but also escaped?

2021-07-08 09:45 UTC, IvanGrginovInf commented on src/Blocks/custom/latest-posts/latest-posts.php
> +					'buttonId' => $blockClass . '__load-more',
This is more of our styleguide thing rather than it being incorrect but always try to use string templating if possible rather than concatenation.

```suggestion
					'buttonId' => "{$blockClass}__load-more",
```

2021-07-08 09:45 UTC, IvanGrginovInf commented on src/Blocks/custom/latest-posts/latest-posts-style.scss
> +		padding: 15px;
Would you know how to reuse this spacing somehow? So for example a designer comes to you and wants to switch this to 30px instead, ideally you'd only have to change a single value rather than 3.

2021-07-08 09:45 UTC, IvanGrginovInf commented on src/Blocks/custom/latest-posts/latest-posts.php
> +$apiNews = $apiNews->getApiData(['limit' => 4]); ?>
Would you know how to do this without instantiating the class here? (if for example, this class had some constructor dependencies it might end up with a lot of class instantiations + you have boilerplatey class wiring logic inside a view).

Hint: you'd only need 1 line here and no class instantiations inside view files (this applies to other blocks / components in general)

2021-07-08 09:45 UTC, IvanGrginovInf commented on src/Blocks/custom/latest-posts/latest-posts.php
> +				class="<?php echo \esc_attr("{$blockClass}__post article-post js-article-post"); ?>"
You could use the `Components::classNames()` helper here. And generally you should use that anytime you have more than 1 class in an element inline. So

```php
$articleClasses = Components::classNames([
  "{$blockClass}__post",
  "article-post",
  "js-article-post"
]);
```

2021-07-08 09:45 UTC, IvanGrginovInf commented on src/Blocks/custom/latest-posts/latest-posts.php
> +						]
Just passing the `'blockClass' => $blockClass` should add a `{$blockClass}__heading` class to the heading component. If not that's an oversight on our parts and you're welcome to modify you own heading component to do just that!

As for `js-{$blockClass}`, that seems a bit weird. Why do you need that class on the heading? Also it seems you're passing that same class on other components as well (such as `paragraph` just below).

Those `js-something` classes should only be used for selecting stuff in JS. This way if you wanted selected `js-block-latest-posts` you would get both the heading & paragraph inside the `block-latest-posts` (which is not intuitive or most likely not what you would have wanted / expected).

2021-07-08 12:55 UTC, simun-ivanac commented on src/Blocks/custom/latest-posts/latest-posts-style.scss
> +		padding: 15px;
Do you think about creating a mixin?

2021-07-08 12:56 UTC, IvanGrginovInf commented on src/Blocks/custom/latest-posts/latest-posts-style.scss
> +		padding: 15px;
Sure, that's one way to do it. Or better yet something even simpler like a SCSS variable. :)

2021-07-08 12:57 UTC, simun-ivanac commented on src/Blocks/custom/latest-posts/latest-posts.php
> +						]
I'm always adding js classes for most of the elements... just a bad habit.
It's fixed now!

2021-07-08 13:00 UTC, simun-ivanac commented on src/Blocks/custom/latest-posts/latest-posts.php
> +$apiNews = $apiNews->getApiData(['limit' => 4]); ?>
The only thing that comes on my mind is making function static :smiley: 
Do you think on that?

2021-07-08 13:03 UTC, IvanGrginovInf commented on src/Blocks/custom/latest-posts/latest-posts.php
> +$apiNews = $apiNews->getApiData(['limit' => 4]); ?>
Was thinking about using a [WP filter](https://developer.wordpress.org/reference/functions/add_filter/) for this but Static class would also kinda work (tho in general you should avoid static classes whenever possible, we try to limit them to helpers only if possible).

2021-07-08 13:04 UTC, simun-ivanac commented on src/Blocks/custom/latest-posts/latest-posts.php
> +					'buttonContent' => __('Load More', 'Assignment'),
using esc_html__()
done!

2021-07-08 13:04 UTC, IvanGrginovInf commented on src/Blocks/custom/latest-posts/latest-posts.php
> +$apiNews = $apiNews->getApiData(['limit' => 4]); ?>
But no need to refactor that for the purposes of this task, how you have it now will do the trick!

2021-07-08 13:23 UTC, simun-ivanac commented on src/Blocks/custom/latest-posts/latest-posts.php
> +$apiNews = $apiNews->getApiData(['limit' => 4]); ?>
I'm gonna try to use filters :smile: 
Just to see how would all work
I can always revert to this

2021-07-08 15:29 UTC, simun-ivanac commented on src/Blocks/custom/latest-posts/latest-posts.php
> +		<?php foreach ($apiNews as $key => $item) : ?>
done!

2021-07-08 15:29 UTC, simun-ivanac commented on src/Blocks/custom/latest-posts/latest-posts.php
> +					'buttonId' => $blockClass . '__load-more',
done!

2021-07-08 15:29 UTC, simun-ivanac commented on src/Blocks/custom/latest-posts/latest-posts-style.scss
> +		padding: 15px;
done!

2021-07-08 15:29 UTC, simun-ivanac commented on src/Blocks/custom/latest-posts/latest-posts.php
> +$apiNews = $apiNews->getApiData(['limit' => 4]); ?>
done!

2021-07-08 15:31 UTC, simun-ivanac commented on src/Blocks/custom/latest-posts/latest-posts.php
> +				class="<?php echo \esc_attr("{$blockClass}__post article-post js-article-post"); ?>"
done!

2021-07-08 17:21 UTC, IvanGrginovInf approved these changes
Looks great, gj on implementing all the suggestions!

2021-07-09 08:18 UTC, dingo-d commented on src/Blocks/custom/latest-posts/latest-posts-style.scss
> +$article-padding: 15px;
This should be an scss map, try to see how other blocks have the variables defined and how they use helpers 🙂

2021-07-09 08:37 UTC, dingo-d commented on src/Blocks/custom/latest-posts/components/latest-posts-options.js
> +		<PanelBody title={__('Latest Post', 'Assignment')}>
If you don't have any options, you can remove them. 

It's a good practice to remove things you don't need. And commit early, just in case you may need to retrieve the thing you later removed 😄

2021-07-09 08:38 UTC, dingo-d commented on src/Blocks/custom/latest-posts/latest-posts.php
> +$apiNews = \apply_filters('get_api_data', ['limit' => $numOfPosts]);
Nice, using the filter to avoid putting logic in the view files 👍🏼

2021-07-09 08:39 UTC, dingo-d commented on src/Blocks/custom/latest-posts/latest-posts.php
> +	echo \wp_kses_post(
You can remove escaping from all the `Components::render` calls, they're safe 👍🏼

2021-07-09 08:40 UTC, dingo-d requested changes
Left couple of comments, good job 👍🏼

2021-07-09 12:13 UTC, simun-ivanac commented on src/Blocks/custom/latest-posts/latest-posts.php
> +	echo \wp_kses_post(
done!

2021-07-09 12:13 UTC, simun-ivanac commented on src/Blocks/custom/latest-posts/latest-posts.php
> +$apiNews = \apply_filters('get_api_data', ['limit' => $numOfPosts]);
thank you :smiley:

2021-07-09 12:13 UTC, simun-ivanac commented on src/Blocks/custom/latest-posts/components/latest-posts-options.js
> +		<PanelBody title={__('Latest Post', 'Assignment')}>
done!

2021-07-09 12:15 UTC, simun-ivanac commented on src/Blocks/custom/latest-posts/latest-posts-style.scss
> +$article-padding: 15px;
done! :smile: 
There are a lot scss helpers
I'll go through them and see if any other is helpful in my case

2021-07-12 08:01 UTC, dingo-d approved these changes
👍🏼

2021-07-12 11:12 UTC, merged